In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Initial overview of the datasets

In [2]:
crime_df = pd.read_csv('../data/On_Street_Crime_In_Camden.csv')

print(crime_df.info())

crime_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151556 entries, 0 to 151555
Data columns (total 20 columns):
Category            151556 non-null object
Street ID           151556 non-null int64
Street Name         151556 non-null object
Context             0 non-null float64
Outcome Category    118117 non-null object
Outcome Date        118117 non-null object
Service             151556 non-null object
Location Subtype    6804 non-null object
ID                  151556 non-null int64
Persistent ID       111777 non-null object
Epoch               151556 non-null object
Ward Code           151556 non-null object
Ward Name           151556 non-null object
Easting             151556 non-null float64
Northing            151556 non-null float64
Longitude           151556 non-null float64
Latitude            151556 non-null float64
Spatial Accuracy    151556 non-null object
Last Uploaded       151556 non-null object
Location            151556 non-null object
dtypes: float64(5), int64(2), object(13)
memory usage: 23.1+ MB
None

,Category,Street ID,Street Name,Context,Outcome Category,Outcome Date,Service,Location Subtype,ID,Persistent ID,Epoch,Ward Code,Ward Name,Easting,Northing,Longitude,Latitude,Spatial Accuracy,Last Uploaded,Location
0,Theft from the person,960684,On or near Conway Mews,NaN,Investigation complete; no suspect identified,01/06/2015,Police Force,NaN,41015103,8b3fa5ae8a1d7c2a018dac3ea65b48d488a72a9088c0ce...,01/05/2015,E05000129,Bloomsbury,529174.85,182002.86,-0.139515,51.522189,This is only an approximation of where the cri...,21/08/2015,"(51.522189, -0.139515)"
1,Burglary,956618,On or near Rathbone Place,NaN,Awaiting court outcome,01/05/2015,Police Force,NaN,38756146,0f2959763b802edd81a586068a3c12cea2855006aa174d...,01/01/2015,E05000129,Bloomsbury,529552.90,181517.86,-0.134247,51.517744,This is only an approximation of where the cri...,21/08/2015,"(51.517744, -0.134247)"
2,Anti-social behaviour,967781,On or near Goldhurst Terrace,NaN,NaN,NaN,Police Force,NaN,44908996,NaN,01/11/2015,E05000133,Frognal and Fitzjohns,526367.86,184618.86,-0.179014,51.546333,This is only an approximation of where the cri...,05/05/2016,"(51.546333, -0.179014)"
3,Anti-social behaviour,960974,On or near Birkenhead Street,NaN,NaN,NaN,Police Force,NaN,44521423,NaN,01/10/2015,E05000141,King's Cross,530392.86,182859.87,-0.121652,51.529611,This is only an approximation of where the cri...,05/05/2016,"(51.529611, -0.121652)"
4,Violence and sexual offences,960582,On or near Shopping Area,NaN,Under investigation,01/02/2018,Police Force,NaN,63282493,130fb7417cd86b5ad345c6c2430ace968837c93b46a08c...,01/02/2018,E05000142,Regent's Park,529585.27,182734.74,-0.133296,51.528664,This is only an approximation of where the cri...,13/04/2018,"(51.528664, -0.133296)"

In [3]:
lighting_df = pd.read_csv('../data/Camden_Street_Lighting.csv')

print(lighting_df.info())

lighting_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9527 entries, 0 to 9526
Data columns (total 13 columns):
Street Name         9510 non-null object
Ward Name           9510 non-null object
Postcode            9509 non-null object
Switch Regime       9527 non-null object
Wattage             9510 non-null float64
Easting             9527 non-null int64
Northing            9527 non-null int64
Longitude           9527 non-null float64
Latitude            9527 non-null float64
Spatial Accuracy    9527 non-null object
Location            9527 non-null object
Organisation URI    9527 non-null object
Last Uploaded       9527 non-null object
dtypes: float64(3), int64(2), object(8)
memory usage: 967.7+ KB
None

,Street Name,Ward Name,Postcode,Switch Regime,Wattage,Easting,Northing,Longitude,Latitude,Spatial Accuracy,Location,Organisation URI,Last Uploaded
0,MILL LANE,FORTUNE GREEN,NW6,35/18,65.0,524803,185110,-0.201358,51.551088,Plotted By Council Officer,"(51.551088, -0.201358)",http://opendatacommunities.org/id/london-borou...,23/08/2018 09:00:09 PM
1,KING HENRY'S ROAD,SWISS COTTAGE,NW3,35/18,90.0,526991,184116,-0.170176,51.541667,Plotted By Council Officer,"(51.541667, -0.170176)",http://opendatacommunities.org/id/london-borou...,23/08/2018 09:00:15 PM
2,PRATT STREET,CAMDEN TOWN,NW1,35/18,90.0,529062,183694,-0.140483,51.537405,Plotted By Council Officer,"(51.537405, -0.140483)",http://opendatacommunities.org/id/london-borou...,23/08/2018 09:00:20 PM
3,HOLLY HILL,HAMPSTEAD TOWN,NW3,70/35,125.0,526343,185793,-0.178913,51.556883,Plotted By Council Officer,"(51.556883, -0.178913)",http://opendatacommunities.org/id/london-borou...,23/08/2018 09:00:13 PM
4,THEOBALD'S ROAD,HOLBORN AND COVENT GARDEN,WC1,35/18,90.0,530787,181882,-0.116298,51.520724,Plotted By Council Officer,"(51.520724, -0.116298)",http://opendatacommunities.org/id/london-borou...,23/08/2018 09:00:27 PM

## Analysis of street lighting dataset

In [4]:
def format_coords(street):
    '''
    Returns a list of coodinates formatted as a tuple of (longitute, latitude)
    
    Args:
        street (pandas.DataFrame): Must contain as lease two columns named 'Longiture' and 'Latitude'
    
    Returns:
        list: Contains tuples of (longitute (float), latitude (float))
        
    '''
    coords = []
    
    (street[['Longitude', 'Latitude']]
     .apply(lambda loc: coords.append((loc['Longitude'], loc['Latitude'])), axis=1))
    
    return coords

In [5]:
# Format coordinates to (long, lat)

coords_sr = (lighting_df
             .groupby(['Ward Name', 'Street Name'])
             .apply(format_coords))

coords_sr.head()

Ward Name  Street Name
BELSIZE    ADAMSON ROAD      [(-0.171694, 51.545153000000006), (-0.171526, ...
           ANTRIM GROVE      [(-0.16188, 51.548542), (-0.162301, 51.5481349...
           ANTRIM ROAD       [(-0.162389, 51.547740999999995), (-0.161373, ...
           BELSIZE AVENUE    [(-0.16813, 51.550241), (-0.166798, 51.551074)...
           BELSIZE GROVE     [(-0.16461800000000001, 51.548244), (-0.16538,...
dtype: object

In [6]:
# Calculate total wattage of each street

wattage_sr = (lighting_df
              .groupby(['Ward Name', 'Street Name'])
              .apply(lambda street: np.sum(street['Wattage'])))

wattage_sr.head()

Ward Name  Street Name
BELSIZE    ADAMSON ROAD       504.0
           ANTRIM GROVE       180.0
           ANTRIM ROAD        360.0
           BELSIZE AVENUE    1170.0
           BELSIZE GROVE      732.0
dtype: float64

In [7]:
# Add total_wattage column to the summary dataframe

summary_df = (pd
              .concat([coords_sr.rename('Coordinates'), wattage_sr.rename('TotalWattage')], axis=1)
              .reset_index())

summary_df.head()

,Ward Name,Street Name,Coordinates,TotalWattage
0,BELSIZE,ADAMSON ROAD,"[(-0.171694, 51.545153000000006), (-0.171526, ...",504.0
1,BELSIZE,ANTRIM GROVE,"[(-0.16188, 51.548542), (-0.162301, 51.5481349...",180.0
2,BELSIZE,ANTRIM ROAD,"[(-0.162389, 51.547740999999995), (-0.161373, ...",360.0
3,BELSIZE,BELSIZE AVENUE,"[(-0.16813, 51.550241), (-0.166798, 51.551074)...",1170.0
4,BELSIZE,BELSIZE GROVE,"[(-0.16461800000000001, 51.548244), (-0.16538,...",732.0

In [8]:
# Calculate area of polygons covered by coordinates
# with transformation to accound for the roundness of the earth

import pyproj
import shapely
import shapely.ops as ops
from shapely.geometry.polygon import Polygon
from functools import partial 

def calculate_area(coords):
    if (len(coords) >= 3):
        geom = Polygon(coords)
        geom_area = ops.transform(partial(pyproj.transform,
                                          pyproj.Proj(init='EPSG:4326'),
                                          pyproj.Proj(proj='aea',
                                                      lat1=geom.bounds[1], 
                                                      lat2=geom.bounds[3])),
                                  geom)

        return geom_area.area  # in m^2

In [9]:
# Summary df with area & lit index (total_wattage / area)

summary_df['Area'] = summary_df['Coordinates'].apply(calculate_area)

summary_df['LitIndex'] = summary_df['TotalWattage'] / summary_df['Area']

summary_df['Ward Name'] = summary_df['Ward Name'].str.lower()
summary_df['Street Name'] = summary_df['Street Name'].str.lower()

summary_df.head()

,Ward Name,Street Name,Coordinates,TotalWattage,Area,LitIndex
0,belsize,adamson road,"[(-0.171694, 51.545153000000006), (-0.171526, ...",504.0,1261.545104,0.399510
1,belsize,antrim grove,"[(-0.16188, 51.548542), (-0.162301, 51.5481349...",180.0,244.861768,0.735109
2,belsize,antrim road,"[(-0.162389, 51.547740999999995), (-0.161373, ...",360.0,540.350583,0.666234
3,belsize,belsize avenue,"[(-0.16813, 51.550241), (-0.166798, 51.551074)...",1170.0,1573.712255,0.743465
4,belsize,belsize grove,"[(-0.16461800000000001, 51.548244), (-0.16538,...",732.0,639.174952,1.145226

## Are lit index & crime count correlated?

In [10]:
# Obtain the total number per category on a street

crime_count_df = (crime_df
                  .groupby(['Ward Name', 'Street Name', 'Category'])
                  .size()
                  .reset_index(name='Count'))

crime_count_df['Ward Name'] = crime_count_df['Ward Name'].str.lower()
crime_count_df['Street Name'] = crime_count_df['Street Name'].str.lower()

crime_count_df.head()

  Ward Name              Street Name                   Category  Count
0   belsize  on or near adamson road      Anti-social behaviour     36
1   belsize  on or near adamson road              Bicycle theft      1
2   belsize  on or near adamson road                   Burglary      7
3   belsize  on or near adamson road  Criminal damage and arson      6
4   belsize  on or near adamson road                      Drugs      1

In [11]:
# Get a list of crime categories

crime_categories = crime_count_df['Category'].unique()

# Create empty columns for each category and total crime count

for category in crime_categories:
    summary_df[category] = 0
    
summary_df['TotalCrimeCount'] = 0

summary_df.head()

,Ward Name,Street Name,Coordinates,TotalWattage,Area,LitIndex,Anti-social behaviour,Bicycle theft,Burglary,Criminal damage and arson,...,Other crime,Other theft,Public order,Robbery,Theft from the person,Vehicle crime,Violence and sexual offences,Possession of weapons,Shoplifting,TotalCrimeCount
0,belsize,adamson road,"[(-0.171694, 51.545153000000006), (-0.171526, ...",504.0,1261.545104,0.399510,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,belsize,antrim grove,"[(-0.16188, 51.548542), (-0.162301, 51.5481349...",180.0,244.861768,0.735109,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,belsize,antrim road,"[(-0.162389, 51.547740999999995), (-0.161373, ...",360.0,540.350583,0.666234,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,belsize,belsize avenue,"[(-0.16813, 51.550241), (-0.166798, 51.551074)...",1170.0,1573.712255,0.743465,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,belsize,belsize grove,"[(-0.16461800000000001, 51.548244), (-0.16538,...",732.0,639.174952,1.145226,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
# Map counts of each crime and total count of all crime per street

def add_crime_count(entry):
    ward_filter = crime_count_df['Ward Name'] == entry['Ward Name'].iloc[0]
    street_filter = crime_count_df['Street Name'].str.lower().str.contains(entry['Street Name'].iloc[0], regex=False)
    
    matching_crime_df = crime_count_df[ward_filter & street_filter]
    
    if not matching_crime_df.empty:
        categories = matching_crime_df['Category']
        total_counts = np.sum(matching_crime_df['Count'])
        entry['TotalCrimeCount'] = total_counts

        for category in categories:
            count = matching_crime_df[matching_crime_df['Category'] == category]['Count'].iloc[0]
            entry[category] = count
        
    return entry

In [13]:
summary_df = summary_df.groupby(['Ward Name', 'Street Name']).apply(add_crime_count)

In [14]:
summary_df.head()

,Ward Name,Street Name,Coordinates,TotalWattage,Area,LitIndex,Anti-social behaviour,Bicycle theft,Burglary,Criminal damage and arson,...,Other crime,Other theft,Public order,Robbery,Theft from the person,Vehicle crime,Violence and sexual offences,Possession of weapons,Shoplifting,TotalCrimeCount
0,belsize,adamson road,"[(-0.171694, 51.545153000000006), (-0.171526, ...",504.0,1261.545104,0.399510,36,1,7,6,...,2,8,4,8,7,14,17,0,0,111
1,belsize,antrim grove,"[(-0.16188, 51.548542), (-0.162301, 51.5481349...",180.0,244.861768,0.735109,88,1,15,7,...,0,1,2,1,6,4,1,0,0,127
2,belsize,antrim road,"[(-0.162389, 51.547740999999995), (-0.161373, ...",360.0,540.350583,0.666234,4,1,5,1,...,0,3,1,2,3,1,1,0,0,24
3,belsize,belsize avenue,"[(-0.16813, 51.550241), (-0.166798, 51.551074)...",1170.0,1573.712255,0.743465,15,1,9,6,...,0,8,2,2,6,9,8,0,0,67
4,belsize,belsize grove,"[(-0.16461800000000001, 51.548244), (-0.16538,...",732.0,639.174952,1.145226,33,4,12,9,...,2,4,5,1,7,16,15,0,0,108

In [15]:
summary_df['CrimeIndex'] = summary_df['TotalCrimeCount'] / summary_df['Area']

summary_df

,Ward Name,Street Name,Coordinates,TotalWattage,Area,LitIndex,Anti-social behaviour,Bicycle theft,Burglary,Criminal damage and arson,...,Other theft,Public order,Robbery,Theft from the person,Vehicle crime,Violence and sexual offences,Possession of weapons,Shoplifting,TotalCrimeCount,CrimeIndex
0,belsize,adamson road,"[(-0.171694, 51.545153000000006), (-0.171526, ...",504.0,1261.545104,0.399510,36,1,7,6,...,8,4,8,7,14,17,0,0,111,0.087987
1,belsize,antrim grove,"[(-0.16188, 51.548542), (-0.162301, 51.5481349...",180.0,244.861768,0.735109,88,1,15,7,...,1,2,1,6,4,1,0,0,127,0.518660
2,belsize,antrim road,"[(-0.162389, 51.547740999999995), (-0.161373, ...",360.0,540.350583,0.666234,4,1,5,1,...,3,1,2,3,1,1,0,0,24,0.044416
3,belsize,belsize avenue,"[(-0.16813, 51.550241), (-0.166798, 51.551074)...",1170.0,1573.712255,0.743465,15,1,9,6,...,8,2,2,6,9,8,0,0,67,0.042574
4,belsize,belsize grove,"[(-0.16461800000000001, 51.548244), (-0.16538,...",732.0,639.174952,1.145226,33,4,12,9,...,4,5,1,7,16,15,0,0,108,0.168968
5,belsize,belsize park gardens,"[(-0.16325499999999998, 51.545929), (-0.170193...",1800.0,21697.619272,0.082958,25,6,18,8,...,9,2,6,6,28,19,0,0,129,0.005945
6,belsize,belsize square,"[(-0.172033, 51.547496), (-0.170915, 51.547694...",1020.0,155.250255,6.570038,31,1,8,6,...,7,6,1,3,24,13,0,0,100,0.644121
7,belsize,belsize terrace,"[(-0.171171, 51.548840000000006), (-0.171205, ...",200.0,NaN,NaN,41,1,6,4,...,11,2,3,6,14,12,0,1,101,NaN
8,belsize,buckland crescent,"[(-0.172794, 51.545781), (-0.173197, 51.545446...",960.0,1063.325622,0.902828,0,0,5,2,...,5,0,2,3,7,4,0,0,29,0.027273
9,belsize,chalcot gardens,"[(-0.161383, 51.546206), (-0.161724, 51.545977...",180.0,0.219515,819.988906,3,0,4,0,...,0,0,0,0,3,0,0,0,10,45.554939
10,belsize,crossfield road,"[(-0.171413, 51.545706), (-0.171343, 51.545992...",420.0,265.291458,1.583164,7,3,6,8,...,10,7,3,5,17,17,0,0,83,0.312863
11,belsize,elizabeth mews,"[(-0.162393, 51.546203000000006), (-0.162603, ...",183.0,200.206614,0.914056,0,1,4,0,...,3,2,0,5,4,2,0,3,24,0.119876
12,belsize,england's lane,"[(-0.161875, 51.546168), (-0.162415, 51.545655...",900.0,503.811467,1.786383,1,1,7,3,...,7,1,0,10,4,6,0,5,45,0.089319
13,belsize,eton avenue,"[(-0.1739, 51.544098999999996), (-0.169303, 51...",2658.0,4495.488960,0.591259,5,1,6,4,...,11,3,9,18,6,8,0,0,74,0.016461
14,belsize,fellows road,"[(-0.163416, 51.544447999999996), (-0.16655799...",2010.0,3303.080128,0.608523,41,2,10,3,...,7,1,6,3,15,12,0,0,102,0.030880
15,belsize,glenilla road,"[(-0.168337, 51.549021), (-0.168704, 51.549234...",450.0,218.947722,2.055285,11,3,14,6,...,12,2,1,3,32,22,0,0,107,0.488701
16,belsize,glenloch road,"[(-0.166751, 51.549365), (-0.16781400000000002...",660.0,221.965968,2.973429,10,0,5,1,...,1,0,1,1,3,0,0,0,22,0.099114
17,belsize,glenmore road,"[(-0.166767, 51.548619), (-0.166454, 51.548857...",420.0,270.408211,1.553207,7,2,6,0,...,1,1,3,1,9,3,0,0,33,0.122038
18,belsize,howitt road,"[(-0.164736, 51.54999), (-0.16566199999999998,...",660.0,873.047662,0.755972,7,0,2,1,...,6,0,0,4,5,4,0,0,29,0.033217
19,belsize,king's college road,"[(-0.169762, 51.544061), (-0.169799, 51.544233...",240.0,128.834640,1.862853,18,2,15,4,...,2,2,8,6,21,9,1,0,90,0.698570
20,belsize,lambolle place,"[(-0.16484100000000002, 51.546646), (-0.165391...",300.0,162.483143,1.846345,0,0,6,0,...,3,1,0,0,6,2,0,0,18,0.110781
21,belsize,lambolle road,"[(-0.16630799999999998, 51.546399), (-0.167575...",480.0,304.315962,1.577308,7,2,9,1,...,1,1,2,0,12,5,0,0,41,0.134728
22,belsize,lancaster drive,"[(-0.168641, 51.54685), (-0.169017, 51.546091)...",240.0,17.672710,13.580261,0,5,5,7,...,3,1,3,1,13,7,0,0,48,2.716052
23,belsize,lancaster grove,"[(-0.170597, 51.54626), (-0.171539, 51.546499)...",1020.0,3794.678566,0.268797,6,0,6,3,...,1,0,1,1,7,0,0,0,25,0.006588
24,belsize,lancaster stables,"[(-0.164686, 51.546563), (-0.164799, 51.546259)]",200.0,NaN,NaN,0,1,1,0,...,0,0,0,0,4,0,0,0,6,NaN
25,belsize,merton rise,"[(-0.166801, 51.544546000000004), (-0.166857, ...",180.0,124.967429,1.440375,0,1,2,2,...,1,2,4,4,4,4,1,8,56,0.448117
26,belsize,ornan road,"[(-0.16936099999999998, 51.550458), (-0.169134...",480.0,300.402819,1.597855,3,1,2,0,...,0,1,0,0,1,1,0,0,9,0.029960
27,belsize,primrose gardens,"[(-0.16430699999999998, 51.548095), (-0.162539...",650.0,5310.997730,0.122388,28,4,12,6,...,4,2,1,3,11,19,0,0,90,0.016946
28,belsize,strathray gardens,"[(-0.16958299999999998, 51.545291), (-0.169667...",360.0,16.918759,21.278157,3,0,4,2,...,3,0,2,4,7,5,0,0,30,1.773180
29,bloomsbury,adeline place,"[(-0.130222, 51.517908), (-0.129623, 51.517421...",300.0,167.852093,1.787288,7,3,3,0,...,4,0,0,0,4,4,0,0,25,0.148941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,west hampstead,fawley road,"[(-0.190389, 51.550146000000005), (-0.18906099...",360.0,321.365767,1.120219,11,2,13,5,...,12,12,2,1,22,13,0,22,117,0.364071
972,west hampstead,footpath north of fortune green through cemete...,"[(-0.198897, 51.555312), (-0.200684, 51.556086...",105.0,430.517543,0.243893,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.000000
973,west hampstead,gladys road,"[(-0.19431600000000002, 51.544604), (-0.193955...",305.0,254.731909,1.197337,1,1,10,1,...,4,0,0,0,11,2,0,0,31,0.121697
974,west hampstead,glenbrook road,"[(-0.19735, 51.550666), (-0.196506, 51.55086),...",244.0,11.510438,21.198152,1,0,3,0,...,1,0,0,0,3,0,0,0,8,0.695021
975,west hampstead,granny dripping steps (footbridge between broa...,"[(-0.18870699999999999, 51.546746999999996), (...",770.0,35.491083,21.695590,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.000000
976,west hampstead,hemstal road,"[(-0.194439, 51.544399), (-0.193181, 51.544496...",720.0,1820.113269,0.395580,25,1,4,7,...,1,1,1,1,15,9,0,0,66,0.036261
977,west hampstead,hilltop road,"[(-0.19306800000000002, 51.545528999999995), (...",225.0,155.625890,1.445775,3,2,9,2,...,3,2,0,1,17,5,0,1,47,0.302006
978,west hampstead,holmdale road,"[(-0.19517, 51.551802), (-0.194943, 51.55134),...",549.0,724.980736,0.757262,26,0,4,5,...,2,1,2,1,8,8,0,0,59,0.081381
979,west hampstead,honeybourne road,"[(-0.190056, 51.550545), (-0.190532, 51.551632...",400.0,97.503459,4.102419,3,1,12,5,...,20,3,1,6,16,10,0,7,85,0.871764
980,west hampstead,inglewood road,"[(-0.193609, 51.550807), (-0.192152, 51.550802...",427.0,190.213809,2.244842,20,1,5,9,...,18,6,0,4,9,11,0,0,85,0.446866
981,west hampstead,iverson road,"[(-0.201481, 51.546135), (-0.194303, 51.547832...",2430.0,7255.624020,0.334913,11,1,7,4,...,3,1,0,3,6,21,0,0,59,0.008132
982,west hampstead,kingdon road,"[(-0.193267, 51.549228), (-0.19248800000000002...",305.0,247.482189,1.232412,21,0,4,2,...,2,0,0,1,4,4,0,0,38,0.153546
983,west hampstead,kylemore road,"[(-0.194953, 51.545621000000004), (-0.19522, 5...",240.0,286.002030,0.839155,6,0,2,4,...,3,0,1,0,9,1,0,0,26,0.090908
984,west hampstead,lithos road,"[(-0.182836, 51.549669), (-0.184104, 51.549329...",366.0,771.377918,0.474476,71,0,5,1,...,6,7,2,1,5,20,0,0,121,0.156862
985,west hampstead,loveridge mews,"[(-0.202355, 51.546274), (-0.202421, 51.546428...",122.0,NaN,NaN,1,1,6,12,...,6,6,1,8,13,32,0,2,100,NaN
986,west hampstead,loveridge road,"[(-0.19917, 51.547304), (-0.199853, 51.54718),...",1530.0,146.311170,10.457165,45,1,17,4,...,18,2,3,10,12,29,0,0,144,0.984204
987,west hampstead,lowfield road,"[(-0.19625399999999998, 51.544813), (-0.195918...",300.0,132.024878,2.272299,9,0,10,4,...,0,0,1,0,3,6,0,1,34,0.257527
988,west hampstead,lymington road,"[(-0.190195, 51.549215999999994), (-0.187021, ...",1170.0,7374.449700,0.158656,2,1,3,1,...,0,0,0,0,2,2,0,0,12,0.001627
989,west hampstead,maygrove road,"[(-0.20161600000000002, 51.547468), (-0.197124...",950.0,19508.608749,0.048696,0,1,6,3,...,6,3,4,0,5,13,0,0,44,0.002255
990,west hampstead,medley road,"[(-0.194734, 51.547164), (-0.194696, 51.547011...",305.0,115.231698,2.646841,15,1,18,11,...,3,16,2,3,4,31,0,0,108,0.937242
991,west hampstead,narcissus road,"[(-0.196021, 51.551815000000005), (-0.19579000...",488.0,919.649614,0.530637,1,0,3,0,...,2,0,1,0,9,3,0,0,19,0.020660
992,west hampstead,pandora road,"[(-0.194803, 51.550151), (-0.195474, 51.549585...",420.0,451.400098,0.930438,4,0,6,1,...,2,0,0,1,15,3,0,0,32,0.070891
993,west hampstead,rosemont road,"[(-0.183099, 51.549224), (-0.183565, 51.549114...",366.0,1211.008338,0.302227,15,1,15,7,...,5,3,0,1,4,5,1,0,58,0.047894
994,west hampstead,sandwell crescent,"[(-0.19175999999999999, 51.54942), (-0.192223,...",183.0,366.589080,0.499197,34,1,20,13,...,27,13,8,10,19,26,1,31,207,0.564665
995,west hampstead,sherriff road,"[(-0.192517, 51.545961), (-0.192948, 51.546003...",549.0,290.358472,1.890766,86,2,8,13,...,3,1,3,0,20,22,0,0,160,0.551043
996,west hampstead,solent road,"[(-0.196448, 51.55014), (-0.19663, 51.550628),...",488.0,185.247120,2.634319,19,0,2,2,...,2,3,0,1,5,5,0,0,39,0.210530
997,west hampstead,sumatra road,"[(-0.196695, 51.549352), (-0.19337200000000002...",1403.0,45409.343438,0.030897,31,1,19,5,...,9,4,3,4,12,12,0,0,101,0.002224
998,west hampstead,west cottages,"[(-0.194003, 51.551038), (-0.19328800000000002...",420.0,144.669846,2.903162,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.000000
999,west hampstead,west end lane,"[(-0.191322, 51.550277), (-0.19325799999999999...",6721.0,324985.406841,0.020681,2,2,19,10,...,22,11,13,41,5,24,2,4,160,0.000492
1000,west hampstead,west hampstead mews,"[(-0.190662, 51.545823999999996), (-0.1898, 51...",366.0,58.386890,6.268531,0,2,5,12,...,4,5,0,0,7,7,0,0,44,0.753594

In [16]:
# Correlation analysis of lit index vs total crime count

summary_df['LitIndex'].corr(summary_df['TotalCrimeCount'])

-0.02152955900659705

In [17]:
# Correlation analysis of lit index vx crime index (both normalised by the area)

summary_df['LitIndex'].corr(summary_df['CrimeIndex'])

0.7332751038619864

In [18]:
# Pairwise correlation for a more fine grained analysis

columns_to_drop = ['Ward Name', 
                   'Street Name', 
                   'Coordinates',
                   'TotalWattage',
                   'Area']

(summary_df
 .drop(columns_to_drop, axis=1)
 .corr(method='spearman')
 .style.format("{:.2}")
 .background_gradient(cmap=plt.get_cmap('coolwarm'), axis=1))